///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HepsiBuradaAyse
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("cdb4a54a-54a3-4500-aedc-929e112d0703", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HepsiBuradaAyseRepository repository.
        /// </summary>
        public static HepsiBuradaAyseRepository repo = HepsiBuradaAyseRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            N5s = "5s";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _N5s;

        /// <summary>
        /// Gets or sets the value of variable N5s.
        /// </summary>
        [TestVariable("f8c8e289-2ca0-4e46-9746-e45b4da447c7")]
        public string N5s
        {
            get { return _N5s; }
            set { _N5s = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // https://www.hepsiburada.com adresini Chrome ile açma
            Report.Log(ReportLevel.Info, "Website", "https://www.hepsiburada.com adresini Chrome ile açma\r\nOpening web site 'https://www.hepsiburada.com' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.hepsiburada.com", "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(1));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Giriş yapma ekranı açma
            Report.Log(ReportLevel.Info, "Mouse", "Giriş yapma ekranı açma\r\nMouse Left Click item 'ApplicationUnderTest.MyAccount' at 17;10.", repo.ApplicationUnderTest.MyAccountInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.MyAccount.Click("17;10");
            Delay.Milliseconds(0);
            
            // Bekleme- 30 ms
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 30 ms\r\nWaiting for 300ms.", new RecordItemIndex(3));
            Delay.Duration(300, false);
            
            // Giriş yapma ekranı açma
            Report.Log(ReportLevel.Info, "Mouse", "Giriş yapma ekranı açma\r\nMouse Left Click item 'ApplicationUnderTest.Login' at Center.", repo.ApplicationUnderTest.LoginInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Login.Click();
            Delay.Milliseconds(0);
            
            // e posta girilen adres doğrulaması
            Report.Log(ReportLevel.Info, "Validation", "e posta girilen adres doğrulaması\r\nValidating CompareImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=1898,Height=520}) on item 'UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info, new RecordItemIndex(5));
            Validate.CompareImage(repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info, DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot1, DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            // e posta text seçimi
            Report.Log(ReportLevel.Info, "Mouse", "e posta text seçimi\r\nMouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName' at Center.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(6));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName.Click();
            Delay.Milliseconds(0);
            
            // HepsiBurada sitesine kayıtlı geçerli bir e posta giriniz-------LÜTFEN VERİ GİRİŞİ YAPINIZ
            Report.Log(ReportLevel.Info, "Keyboard", "HepsiBurada sitesine kayıtlı geçerli bir e posta giriniz-------LÜTFEN VERİ GİRİŞİ YAPINIZ\r\nKey sequence 'xxxxxxxxx@hotmail.com' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(7));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName.EnsureVisible();
            Keyboard.Press("xxxxxxxxx@hotmail.com");
            Delay.Milliseconds(0);
            
            // giriş yap butonu seçimi
            Report.Log(ReportLevel.Info, "Mouse", "giriş yap butonu seçimi\r\nMouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin' at Center.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLoginInfo, new RecordItemIndex(8));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin.Click();
            Delay.Milliseconds(0);
            
            // şifre girilen adres doğrulaması
            Report.Log(ReportLevel.Info, "Validation", "şifre girilen adres doğrulaması\r\nValidating CompareImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=1898,Height=622}) on item 'UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info, new RecordItemIndex(9));
            Validate.CompareImage(repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info, DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot2, DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            // şifre text seçimi
            Report.Log(ReportLevel.Info, "Mouse", "şifre text seçimi\r\nMouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword' at Center.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(10));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.Click();
            Delay.Milliseconds(0);
            
            // HepsiBurada sitesine kayıtlı geçerli e postanın şifresini giriniz-------LÜTFEN VERİ GİRİŞİ YAPINIZ
            Report.Log(ReportLevel.Info, "Keyboard", "HepsiBurada sitesine kayıtlı geçerli e postanın şifresini giriniz-------LÜTFEN VERİ GİRİŞİ YAPINIZ\r\nKey sequence 'xxxxxxxxxx' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(11));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.EnsureVisible();
            Keyboard.Press("xxxxxxxxxx");
            Delay.Milliseconds(0);
            
            // giriş yap butonu seçimi
            Report.Log(ReportLevel.Info, "Mouse", "giriş yap butonu seçimi\r\nMouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect' at Center.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelectInfo, new RecordItemIndex(12));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 30 ms
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 30 ms\r\nWaiting for 300ms.", new RecordItemIndex(13));
            Delay.Duration(300, false);
            
            // arama text seçimi
            Report.Log(ReportLevel.Info, "Mouse", "arama text seçimi\r\nMouse Left Click item 'ApplicationUnderTest.SearchBoxOld.Text' at Center.", repo.ApplicationUnderTest.SearchBoxOld.TextInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.SearchBoxOld.Text.Click();
            Delay.Milliseconds(0);
            
            // Doğan Cüceloğlu arama
            Report.Log(ReportLevel.Info, "Keyboard", "Doğan Cüceloğlu arama\r\nKey sequence 'Doğan Cüceloğlu' with focus on 'ApplicationUnderTest.SearchBoxOld.Text'.", repo.ApplicationUnderTest.SearchBoxOld.TextInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.SearchBoxOld.Text.EnsureVisible();
            Keyboard.Press("Doğan Cüceloğlu");
            Delay.Milliseconds(0);
            
            // Enter butonu
            Report.Log(ReportLevel.Info, "Keyboard", "Enter butonu\r\nKey sequence '{Return}' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            // Bekleme- 30 ms
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 30 ms\r\nWaiting for 300ms.", new RecordItemIndex(17));
            Delay.Duration(300, false);
            
            // "Doğan Cüceloğlu- Var mısın" kitabının seçimi
            Report.Log(ReportLevel.Info, "Mouse", "\"Doğan Cüceloğlu- Var mısın\" kitabının seçimi\r\nMouse Left Click item 'ApplicationUnderTest.HttpsProductimagesHepsiburadaNetS' at 84;259.", repo.ApplicationUnderTest.HttpsProductimagesHepsiburadaNetSInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.HttpsProductimagesHepsiburadaNetS.Click("84;259");
            Delay.Milliseconds(0);
            
            // Lokasyon düzenleme
            Report.Log(ReportLevel.Info, "Mouse", "Lokasyon düzenleme\r\nMouse scroll Vertical by -360 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(300);
            
            // Sepete Ekle button seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Sepete Ekle button seçimi\r\nMouse Left Click item 'ApplicationUnderTest.AddToCart' at Center.", repo.ApplicationUnderTest.AddToCartInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.AddToCart.Click();
            Delay.Milliseconds(0);
            
            // Sepetim buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Sepetim buton seçimi\r\nMouse Left Click item 'ApplicationUnderTest.ShoppingCart' at Center.", repo.ApplicationUnderTest.ShoppingCartInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.ShoppingCart.Click();
            Delay.Milliseconds(0);
            
            // Bekleme-30 ms
            Report.Log(ReportLevel.Info, "Delay", "Bekleme-30 ms\r\nWaiting for 300ms.", new RecordItemIndex(22));
            Delay.Duration(300, false);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(23));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(24));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDeğiştir' at Center.", repo.Sepetim.ATagDeğiştirInfo, new RecordItemIndex(25));
            repo.Sepetim.ATagDeğiştir.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(26));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(27));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - Akbank
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - Akbank\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.Akbank' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.AkbankInfo, new RecordItemIndex(28));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.Akbank.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(29));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - Akbank
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - Akbank\r\nValidating AttributeEqual (InnerText='Akbank') on item 'Sepetim.PaymentDetails1v4iX1.Akbank'.", repo.Sepetim.PaymentDetails1v4iX1.AkbankInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.AkbankInfo, "InnerText", "Akbank");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.Akbank' at Center.", repo.Sepetim.PaymentDetails1v4iX1.AkbankInfo, new RecordItemIndex(31));
            repo.Sepetim.PaymentDetails1v4iX1.Akbank.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - Akbank
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(32));
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDuezenle' at Center.", repo.Sepetim.ATagDuezenleInfo, new RecordItemIndex(33));
            repo.Sepetim.ATagDuezenle.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(34));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(35));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - İş Bankası
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - İş Bankası\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.İşBankası' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.İşBankasıInfo, new RecordItemIndex(36));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.İşBankası.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(37));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - İş Bankası
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - İş Bankası\r\nValidating AttributeEqual (InnerText='İş Bankası') on item 'Sepetim.PaymentDetails1v4iX1.İşBankası'.", repo.Sepetim.PaymentDetails1v4iX1.İşBankasıInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.İşBankasıInfo, "InnerText", "İş Bankası");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.İşBankası' at Center.", repo.Sepetim.PaymentDetails1v4iX1.İşBankasıInfo, new RecordItemIndex(39));
            repo.Sepetim.PaymentDetails1v4iX1.İşBankası.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - İş Bankası
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(40));
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDuezenle' at Center.", repo.Sepetim.ATagDuezenleInfo, new RecordItemIndex(41));
            repo.Sepetim.ATagDuezenle.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(42));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(43));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - Kuveyt Türk
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - Kuveyt Türk\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.KuveytTuerk' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.KuveytTuerkInfo, new RecordItemIndex(44));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.KuveytTuerk.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(45));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - Kuveyt Türk
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - Kuveyt Türk\r\nValidating AttributeEqual (InnerText='Kuveyt Türk') on item 'Sepetim.PaymentDetails1v4iX1.KuveytTuerk'.", repo.Sepetim.PaymentDetails1v4iX1.KuveytTuerkInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.KuveytTuerkInfo, "InnerText", "Kuveyt Türk");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.KuveytTuerk' at Center.", repo.Sepetim.PaymentDetails1v4iX1.KuveytTuerkInfo, new RecordItemIndex(47));
            repo.Sepetim.PaymentDetails1v4iX1.KuveytTuerk.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - Kuveyt Turk
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(48));
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDuezenle' at Center.", repo.Sepetim.ATagDuezenleInfo, new RecordItemIndex(49));
            repo.Sepetim.ATagDuezenle.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(50));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(51));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - Fibabanka
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - Fibabanka\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.Fibabanka' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.FibabankaInfo, new RecordItemIndex(52));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.Fibabanka.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(53));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - Fibabanka
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - Fibabanka\r\nValidating AttributeEqual (InnerText='Fibabanka') on item 'Sepetim.PaymentDetails1v4iX1.Fibabanka'.", repo.Sepetim.PaymentDetails1v4iX1.FibabankaInfo, new RecordItemIndex(54));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.FibabankaInfo, "InnerText", "Fibabanka");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.Fibabanka' at Center.", repo.Sepetim.PaymentDetails1v4iX1.FibabankaInfo, new RecordItemIndex(55));
            repo.Sepetim.PaymentDetails1v4iX1.Fibabanka.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - Fibabanka
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(56));
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDuezenle' at Center.", repo.Sepetim.ATagDuezenleInfo, new RecordItemIndex(57));
            repo.Sepetim.ATagDuezenle.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(58));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(59));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - Vakıfbank
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - Vakıfbank\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.Vakıfbank' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.VakıfbankInfo, new RecordItemIndex(60));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.Vakıfbank.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(61));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - Vakıfbank
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - Vakıfbank\r\nValidating AttributeEqual (InnerText='Vakıfbank') on item 'Sepetim.PaymentDetails1v4iX1.Vakıfbank'.", repo.Sepetim.PaymentDetails1v4iX1.VakıfbankInfo, new RecordItemIndex(62));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.VakıfbankInfo, "InnerText", "Vakıfbank");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.Vakıfbank' at Center.", repo.Sepetim.PaymentDetails1v4iX1.VakıfbankInfo, new RecordItemIndex(63));
            repo.Sepetim.PaymentDetails1v4iX1.Vakıfbank.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - Vakıfbank
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(64));
            
            // Ödeme yöntemi değiştirme
            Report.Log(ReportLevel.Info, "Mouse", "Ödeme yöntemi değiştirme\r\nMouse Left Click item 'Sepetim.ATagDuezenle' at Center.", repo.Sepetim.ATagDuezenleInfo, new RecordItemIndex(65));
            repo.Sepetim.ATagDuezenle.Click();
            Delay.Milliseconds(0);
            
            // Bekleme- 5 s
            Report.Log(ReportLevel.Info, "Delay", "Bekleme- 5 s\r\nWaiting for time from variable $N5s.", new RecordItemIndex(66));
            Delay.Duration(Duration.Parse(N5s), false);
            
            // Anında havale seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Anında havale seçimi\r\nMouse Left Click item 'Sepetim.AnındaHavale' at Center.", repo.Sepetim.AnındaHavaleInfo, new RecordItemIndex(67));
            repo.Sepetim.AnındaHavale.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi - AlBaraka Türk
            Report.Log(ReportLevel.Info, "Mouse", "Banka seçimi - AlBaraka Türk\r\nMouse Left Click item 'Sepetim.SardesPaymentPageAccordionNonGroupSa.AlBarakaTuerk' at Center.", repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.AlBarakaTuerkInfo, new RecordItemIndex(68));
            repo.Sepetim.SardesPaymentPageAccordionNonGroupSa.AlBarakaTuerk.Click();
            Delay.Milliseconds(0);
            
            // Alışverişi tamamla buton seçimi
            Report.Log(ReportLevel.Info, "Mouse", "Alışverişi tamamla buton seçimi\r\nMouse Left Click item 'Sepetim.ContinueStepBtn' at Center.", repo.Sepetim.ContinueStepBtnInfo, new RecordItemIndex(69));
            repo.Sepetim.ContinueStepBtn.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu - AlBaraka Türk
            Report.Log(ReportLevel.Info, "Validation", "Banka seçimi kotrolu - AlBaraka Türk\r\nValidating AttributeEqual (InnerText='AlBaraka Türk') on item 'Sepetim.PaymentDetails1v4iX1.AlBarakaTuerk'.", repo.Sepetim.PaymentDetails1v4iX1.AlBarakaTuerkInfo, new RecordItemIndex(70));
            Validate.AttributeEqual(repo.Sepetim.PaymentDetails1v4iX1.AlBarakaTuerkInfo, "InnerText", "AlBaraka Türk");
            Delay.Milliseconds(100);
            
            // Mouse ile gösterim- Banka seçimi kotrolu
            Report.Log(ReportLevel.Info, "Mouse", "Mouse ile gösterim- Banka seçimi kotrolu\r\nMouse Left Click item 'Sepetim.PaymentDetails1v4iX1.AlBarakaTuerk' at Center.", repo.Sepetim.PaymentDetails1v4iX1.AlBarakaTuerkInfo, new RecordItemIndex(71));
            repo.Sepetim.PaymentDetails1v4iX1.AlBarakaTuerk.Click();
            Delay.Milliseconds(0);
            
            // Banka seçimi kotrolu raporlaması - AlBaraka Türk
            Report.Log(ReportLevel.Success, "User", "Selected bank and displayed on paypage are match.", new RecordItemIndex(72));
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot1
        { get { return repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info.GetScreenshot1(new Rectangle(0, 0, 1898, 520)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.98;EdgesSobel;0,0,1898,520;True;10000000;0ms"); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot2
        { get { return repo.UEyeGirişSayfasıUEyeOlHepsiburad.DivTag2zMNDEK0DU0JIXaIzA2Jl1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info.GetScreenshot2(new Rectangle(0, 0, 1898, 622)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions DivTag1qzyrDtuo5Y1fZvzzhrn3_Screenshot2_Options
        { get { return Imaging.FindOptions.Parse("0.98;EdgesSobel;0,0,1898,622;True;10000000;0ms"); } }

#endregion
    }
#pragma warning restore 0436
}
